/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-04-26 00:45:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class question_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/class/project/jsp.servlet/GoodJob/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/GoodJob/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/inc/asset.jsp", Long.valueOf(1714091923566L));
    _jspx_dependants.put("/WEB-INF/views/inc/header.jsp", Long.valueOf(1714091923567L));
    _jspx_dependants.put("/WEB-INF/views/inc/footer.jsp", Long.valueOf(1714091923567L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1714091923532L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- favicon -->\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"/good/asset/images/favicon.ico\" />\r\n");
      out.write("<!-- <link rel=\"icon\" href=\"/good/asset/favicon.ico\" type=\"image/x-icon\"> -->\r\n");
      out.write("\r\n");
      out.write("<!-- theme meta -->\r\n");
      out.write("<meta name=\"theme-name\" content=\"Pinwheel\" />\r\n");
      out.write("<meta name=\"msapplication-TileColor\" content=\"#000000\" />\r\n");
      out.write("<meta name=\"theme-color\" media=\"(prefers-color-scheme: light)\"\r\n");
      out.write("	content=\"#fff\" />\r\n");
      out.write("<meta name=\"theme-color\" media=\"(prefers-color-scheme: dark)\"\r\n");
      out.write("	content=\"#000\" />\r\n");
      out.write("<meta name=\"generator\" content=\"gulp\" />\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("\r\n");
      out.write("<!-- responsive meta -->\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, maximum-scale=5\" />\r\n");
      out.write("\r\n");
      out.write("<!-- title -->\r\n");
      out.write("<title>Good Job</title>\r\n");
      out.write("\r\n");
      out.write("<!-- noindex robots -->\r\n");
      out.write("<meta name=\"robots\" content=\"\" />\r\n");
      out.write("\r\n");
      out.write("<!-- meta-description -->\r\n");
      out.write("<meta name=\"description\" content=\"meta description\" />\r\n");
      out.write("\r\n");
      out.write("<!-- author from config.json -->\r\n");
      out.write("<meta name=\"author\" content=\"{config.metadata.meta_author}\" />\r\n");
      out.write("\r\n");
      out.write("<!-- og-title -->\r\n");
      out.write("<meta property=\"og:title\" content=\"\" />\r\n");
      out.write("\r\n");
      out.write("<!-- og-description -->\r\n");
      out.write("<meta property=\"og:description\" content=\"\" />\r\n");
      out.write("<meta property=\"og:type\" content=\"website\" />\r\n");
      out.write("<meta property=\"og:url\" content=\"/\" />\r\n");
      out.write("\r\n");
      out.write("<!-- twitter-title -->\r\n");
      out.write("<meta name=\"twitter:title\" content=\"\" />\r\n");
      out.write("\r\n");
      out.write("<!-- twitter-description -->\r\n");
      out.write("<meta name=\"twitter:description\" content=\"\" />\r\n");
      out.write("\r\n");
      out.write("<!-- og-image -->\r\n");
      out.write("<meta property=\"og:image\" content=\"\" />\r\n");
      out.write("\r\n");
      out.write("<!-- twitter-image -->\r\n");
      out.write("<meta name=\"twitter:image\" content=\"\" />\r\n");
      out.write("<meta name=\"twitter:card\" content=\"summary_large_image\" />\r\n");
      out.write("\r\n");
      out.write("<!-- google font css -->\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\" />\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin />\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\" />\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Merriweather:wght@700;900&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("<!-- styles -->\r\n");
      out.write("\r\n");
      out.write("<!-- Swiper slider -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/good/asset/plugins/swiper/swiper-bundle.css\" />\r\n");
      out.write("\r\n");
      out.write("<!-- Fontawesome -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/good/asset/plugins/font-awesome/v6/brands.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/good/asset/plugins/font-awesome/v6/solid.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/good/asset/plugins/font-awesome/v6/fontawesome.css\" />\r\n");
      out.write("\r\n");
      out.write("<!-- Main Stylesheet -->\r\n");
      out.write("<link href=\"/good/asset/styles/main.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery -->\r\n");
      out.write("<script src=\"/good/asset/plugins/jquery/jquery.min.js\"></script>\r\n");
      out.write("<!-- Swiper JS -->\r\n");
      out.write("<script src=\"/good/asset/plugins/swiper/swiper-bundle.js\"></script>\r\n");
      out.write("<script src=\"/good/asset/plugins/shufflejs/shuffle.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Main Script -->\r\n");
      out.write("<script src=\"/good/asset/scripts/main.js\"></script>");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<header class=\"header\">\r\n");
      out.write("  <nav class=\"navbar container\">\r\n");
      out.write("    <!-- logo -->\r\n");
      out.write("    <div class=\"order-0\">\r\n");
      out.write("      <a href=\"index.html\">\r\n");
      out.write("        <img src=\"images/logo.svg\" height=\"30\" width=\"147\" alt=\"logo\" />\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- navbar toggler -->\r\n");
      out.write("    <input id=\"nav-toggle\" type=\"checkbox\" class=\"hidden\" />\r\n");
      out.write("    <label\r\n");
      out.write("      id=\"show-button\"\r\n");
      out.write("      for=\"nav-toggle\"\r\n");
      out.write("      class=\"order-1 flex cursor-pointer items-center lg:order-1 lg:hidden\"\r\n");
      out.write("    >\r\n");
      out.write("      <svg class=\"h-6 fill-current\" viewBox=\"0 0 20 20\">\r\n");
      out.write("        <title>Menu Open</title>\r\n");
      out.write("        <path d=\"M0 3h20v2H0V3z m0 6h20v2H0V9z m0 6h20v2H0V0z\"></path>\r\n");
      out.write("      </svg>\r\n");
      out.write("    </label>\r\n");
      out.write("    <label\r\n");
      out.write("      id=\"hide-button\"\r\n");
      out.write("      for=\"nav-toggle\"\r\n");
      out.write("      class=\"order-2 hidden cursor-pointer items-center lg:order-1\"\r\n");
      out.write("    >\r\n");
      out.write("      <svg class=\"h-6 fill-current\" viewBox=\"0 0 20 20\">\r\n");
      out.write("        <title>Menu Close</title>\r\n");
      out.write("        <polygon\r\n");
      out.write("          points=\"11 9 22 9 22 11 11 11 11 22 9 22 9 11 -2 11 -2 9 9 9 9 -2 11 -2\"\r\n");
      out.write("          transform=\"rotate(45 10 10)\"\r\n");
      out.write("        ></polygon>\r\n");
      out.write("      </svg>\r\n");
      out.write("    </label>\r\n");
      out.write("    <!-- /navbar toggler -->\r\n");
      out.write("    <ul\r\n");
      out.write("      id=\"nav-menu\"\r\n");
      out.write("      class=\"navbar-nav order-2 hidden w-full flex-[0_0_100%] lg:order-1 lg:flex lg:w-auto lg:flex-auto lg:justify-center lg:space-x-5\"\r\n");
      out.write("    >\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a href=\"\" class=\"nav-link active\">Home</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a href=\"about.html\" class=\"nav-link\">About</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a href=\"blog.html\" class=\"nav-link\">Blog</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a href=\"features.html\" class=\"nav-link\">Features</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a href=\"how-it-works.html\" class=\"nav-link\">How It Works</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item nav-dropdown group relative\">\r\n");
      out.write("        <span class=\"nav-link inline-flex items-center\">\r\n");
      out.write("          Pages\r\n");
      out.write("          <svg class=\"h-4 w-4 fill-current\" viewBox=\"0 0 20 20\">\r\n");
      out.write("            <path\r\n");
      out.write("              d=\"M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z\"\r\n");
      out.write("            />\r\n");
      out.write("          </svg>\r\n");
      out.write("        </span>\r\n");
      out.write("        <ul\r\n");
      out.write("          class=\"nav-dropdown-list hidden group-hover:block lg:invisible lg:absolute lg:block lg:opacity-0 lg:group-hover:visible lg:group-hover:opacity-100\"\r\n");
      out.write("        >\r\n");
      out.write("          <li class=\"nav-dropdown-item\">\r\n");
      out.write("            <a href=\"career.html\" class=\"nav-dropdown-link\">Career</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-dropdown-item\">\r\n");
      out.write("            <a href=\"career-single.html\" class=\"nav-dropdown-link\"\r\n");
      out.write("              >Career Single</a\r\n");
      out.write("            >\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-dropdown-item\">\r\n");
      out.write("            <a href=\"integrations.html\" class=\"nav-dropdown-link\"\r\n");
      out.write("              >Integrations</a\r\n");
      out.write("            >\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-dropdown-item\">\r\n");
      out.write("            <a href=\"integration-single.html\" class=\"nav-dropdown-link\"\r\n");
      out.write("              >Integration Single</a\r\n");
      out.write("            >\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-dropdown-item\">\r\n");
      out.write("            <a href=\"pricing.html\" class=\"nav-dropdown-link\">Pricing</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-dropdown-item\">\r\n");
      out.write("            <a href=\"changelogs.html\" class=\"nav-dropdown-link\">Changelogs</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-dropdown-item\">\r\n");
      out.write("            <a href=\"terms-conditions.html\" class=\"nav-dropdown-link\"\r\n");
      out.write("              >Terms & Conditions</a\r\n");
      out.write("            >\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a href=\"contact.html\" class=\"nav-link\">Contact</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item mt-3.5 lg:hidden\">\r\n");
      out.write("        <a class=\"btn btn-white btn-sm border-border\" href=\"signin.html\"\r\n");
      out.write("          >Sing Up Now</a\r\n");
      out.write("        >\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    <div class=\"order-1 ml-auto hidden items-center md:order-2 md:ml-0 lg:flex\">\r\n");
      out.write("      <a class=\"btn btn-white btn-sm\" href=\"signin.html\">Sing Up Now</a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>\r\n");
      out.write("</header>");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<img\r\n");
      out.write("  class=\"floating-bubble-1 absolute right-0 top-0 -z-[1]\"\r\n");
      out.write("  src=\"images/floating-bubble-1.svg\"\r\n");
      out.write("  alt=\"\"\r\n");
      out.write("/>\r\n");
      out.write("<img\r\n");
      out.write("  class=\"floating-bubble-2 absolute left-0 top-[387px] -z-[1]\"\r\n");
      out.write("  src=\"images/floating-bubble-2.svg\"\r\n");
      out.write("  alt=\"\"\r\n");
      out.write("/>\r\n");
      out.write("<img\r\n");
      out.write("  class=\"floating-bubble-3 absolute right-0 top-[605px] -z-[1]\"\r\n");
      out.write("  src=\"images/floating-bubble-3.svg\"\r\n");
      out.write("  alt=\"\"\r\n");
      out.write("/>\r\n");
      out.write("<!-- ./end floating assets -->\r\n");
      out.write("\r\n");
      out.write("<!-- blog single -->\r\n");
      out.write("<section class=\"section blog-single\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <div class=\"row justify-center\">\r\n");
      out.write("      <div class=\"lg:col-10\">\r\n");
      out.write("        <img class=\"rounded-xl\" src=\"images/blog-single.png\" alt=\"\" />\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"mt-10 max-w-[810px] lg:col-9\">\r\n");
      out.write("        <h1 class=\"h2\">\r\n");
      out.write("          Memo To All Housekeeping, Kitchen, & Dining Room Staff At Mar-A-Lago\r\n");
      out.write("        </h1>\r\n");
      out.write("        <div class=\"mt-6 mb-5 flex items-center space-x-2\">\r\n");
      out.write("          <div\r\n");
      out.write("            class=\"blog-author-avatar h-[58px] w-[58px] rounded-full border-2 border-primary p-0.5\"\r\n");
      out.write("          >\r\n");
      out.write("            <img src=\"images/blog-author.png\" alt=\"\" />\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"\">\r\n");
      out.write("            <p class=\"text-dark\">Cameron Williamson</p>\r\n");
      out.write("            <span class=\"text-sm\">Nov 28, 2019. 5 Min read</span>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"content\">\r\n");
      out.write("          <p>\r\n");
      out.write("            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nec et\r\n");
      out.write("            ipsum ullamcorper venenatis fringilla. Pretium, purus eu nec\r\n");
      out.write("            vulputate vel habitant egestas. Congue ornare at ipsum, viverra.\r\n");
      out.write("            Vitae magna faucibus eros, lectus sociis. Etiam nunc amet id\r\n");
      out.write("            dignissim. Feugiat id tempor vel sit in ornare turpis posuere. Eu\r\n");
      out.write("            quisque integer non rhoncus elementum vel. Quis nec viverra lectus\r\n");
      out.write("            augue nec praesent Laoreet mauris odio ut nec. Nisl, sed adipiscing\r\n");
      out.write("            dignissim arcu placerat ornare pharetra nec in. Ultrices in nisl\r\n");
      out.write("            potenti vitae tempus. Auctor consectetur luctus eu in amet sagittis.\r\n");
      out.write("            Dis urna, vel hendrerit convallis Senectus feugiat faucibus commodo\r\n");
      out.write("            egestas leo vitae in morbi. Enim arcu dignissim mauris, eu, eget\r\n");
      out.write("          </p>\r\n");
      out.write("\r\n");
      out.write("          <p>\r\n");
      out.write("            pharetra odio amet pellentesque. Egestas nisi adipiscing sed in\r\n");
      out.write("            lectus. Vitae ultrices malesuada aliquet Faucibus consectetur tempus\r\n");
      out.write("            adipiscing vitae. Nec blandit tincidunt nibh nisi, quam volutpat. In\r\n");
      out.write("            lacus laoreet diam risus. Mauris, risus faucibus sagittis sagittis\r\n");
      out.write("            tincidunt id justo. Diam massa pretium consequat mauris viverra.\r\n");
      out.write("            Sagittis eu libero\r\n");
      out.write("          </p>\r\n");
      out.write("          <div class=\"blockquote my-10 rounded-xl bg-white py-8 px-16 lg:px-20\">\r\n");
      out.write("            <blockquote class=\"text-2xl text-dark\">\r\n");
      out.write("              A wise girls her limit to touch.To Repellat neque praesentium .The\r\n");
      out.write("              me an idea, so I as quickly To get.\r\n");
      out.write("            </blockquote>\r\n");
      out.write("            <p class=\"mt-4 mb-0\">Darlene Robertson</p>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <p>\r\n");
      out.write("            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nec et\r\n");
      out.write("            ipsum ullamcorper venenatis fringilla. Pretium, purus eu nec\r\n");
      out.write("            vulputate vel habitant egestas. Congue ornare at ipsum, viverra.\r\n");
      out.write("            Vitae magna faucibus eros, lectus sociis. Etiam nunc amet id\r\n");
      out.write("            dignissim. Feugiat id tempor vel sit in ornare turpis posuere. Eu\r\n");
      out.write("            quisque integer non rhoncus elementum vel. Quis nec viverra lectus\r\n");
      out.write("            augue nec praesent volutpat tortor. Ipsum eget sed tempus luctus\r\n");
      out.write("            nisl. Ut etiam molestie mattis at faucibus mi at pellentesque.\r\n");
      out.write("            Pellentesque morbi nunc, curabitur arcu euismod suscipit. Duis mi\r\n");
      out.write("            sapien, nisl, pulvinar donec non dictum\r\n");
      out.write("          </p>\r\n");
      out.write("\r\n");
      out.write("          <p>\r\n");
      out.write("            Laoreet mauris odio ut nec. Nisl, sed adipiscing dignissim arcu\r\n");
      out.write("            placerat ornare pharetra nec in. Ultrices in nisl potenti vitae\r\n");
      out.write("            tempus. Auctor consectetur luctus eu in amet sagittis. Dis urna, vel\r\n");
      out.write("            hendrerit convallis cursus id. Senectus feugiat faucibus commodo\r\n");
      out.write("            egestas leo vitae in morbi. Enim arcu dignissim mauris, eu, eget\r\n");
      out.write("            pharetra odio amet pellentesque. Egestas nisi adipiscing sed in\r\n");
      out.write("            lectus. Vitae ultrices malesuada aliquet dignissim. Faucibus non\r\n");
      out.write("            tristique eu.\r\n");
      out.write("          </p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"comments\">\r\n");
      out.write("          <h3\r\n");
      out.write("            class=\"h5 inline-block border-b-[3px] border-primary font-primary font-medium leading-8\"\r\n");
      out.write("          >\r\n");
      out.write("            Comments\r\n");
      out.write("          </h3>\r\n");
      out.write("          <div class=\"comment flex space-x-4 border-b border-border py-8\">\r\n");
      out.write("            <img\r\n");
      out.write("              src=\"images/comment-author-1.png\"\r\n");
      out.write("              class=\"h-[70px] w-[70px] rounded-full\"\r\n");
      out.write("              alt=\"\"\r\n");
      out.write("            />\r\n");
      out.write("            <div>\r\n");
      out.write("              <h4 class=\"font-primary text-lg font-medium capitalize\">\r\n");
      out.write("                ronin bishop\r\n");
      out.write("              </h4>\r\n");
      out.write("              <p class=\"mt-2.5\">\r\n");
      out.write("                April 18, 2020 at 6.25 pm\r\n");
      out.write("                <a class=\"ml-4 text-primary\" href=\"#\">Replay</a>\r\n");
      out.write("              </p>\r\n");
      out.write("              <p class=\"mt-5\">\r\n");
      out.write("                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nec et\r\n");
      out.write("                ipsum ullamcorper venenatis fringilla. Pretium, purus eu nec\r\n");
      out.write("                vulputate vel habitant egestas.ornare ipsum\r\n");
      out.write("              </p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"comment flex space-x-4 py-8\">\r\n");
      out.write("            <img src=\"images/icons/replay-arrow.svg\" alt=\"\" />\r\n");
      out.write("            <img\r\n");
      out.write("              src=\"images/comment-author-2.png\"\r\n");
      out.write("              class=\"h-[70px] w-[70px] rounded-full\"\r\n");
      out.write("              alt=\"\"\r\n");
      out.write("            />\r\n");
      out.write("            <div>\r\n");
      out.write("              <h4 class=\"font-primary text-lg font-medium capitalize\">\r\n");
      out.write("                Kathryn Murphy\r\n");
      out.write("              </h4>\r\n");
      out.write("              <p class=\"mt-2.5\">\r\n");
      out.write("                April 18, 2020 at 6.25 pm\r\n");
      out.write("                <a class=\"ml-4 text-primary\" href=\"#\">Replay</a>\r\n");
      out.write("              </p>\r\n");
      out.write("              <p class=\"mt-5\">\r\n");
      out.write("                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nec et\r\n");
      out.write("                ipsum ullamcorper venenatis fringilla. Pretium, purus eu nec\r\n");
      out.write("                vulputate vel habitant egestas.ornare ipsum\r\n");
      out.write("              </p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <form class=\"comment-form\" action=\"#\" method=\"POST\">\r\n");
      out.write("          <p class=\"mb-4\">LEAVE A REPLAY</p>\r\n");
      out.write("          <div class=\"form-group\">\r\n");
      out.write("            <textarea cols=\"30\" rows=\"10\"></textarea>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"row mb-8\">\r\n");
      out.write("            <div class=\"form-group mt-8 md:col-6 lg:col-4\">\r\n");
      out.write("              <input type=\"text\" placeholder=\"Name\" />\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group mt-8 md:col-6 lg:col-4\">\r\n");
      out.write("              <input type=\"text\" placeholder=\"Email\" />\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group mt-8 md:col-6 lg:col-4\">\r\n");
      out.write("              <input type=\"text\" placeholder=\"Website\" />\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"form-group relative flex pl-6\">\r\n");
      out.write("            <input\r\n");
      out.write("              class=\"absolute left-0 top-1\"\r\n");
      out.write("              type=\"checkbox\"\r\n");
      out.write("              id=\"save-info\"\r\n");
      out.write("            />\r\n");
      out.write("            <label class=\"block\" for=\"save-info\"\r\n");
      out.write("              >Save my name, email, and website in this browser for the next\r\n");
      out.write("              time I comment.</label\r\n");
      out.write("            >\r\n");
      out.write("          </div>\r\n");
      out.write("          <input\r\n");
      out.write("            type=\"Submit\"\r\n");
      out.write("            class=\"btn btn-primary mt-8 min-w-[189px] cursor-pointer\"\r\n");
      out.write("            value=\"Post Comment\"\r\n");
      out.write("          />\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</section>	\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<footer class=\"footer bg-theme-light/50\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <div class=\"row gx-5 pb-10 pt-[52px]\">\r\n");
      out.write("      <div class=\"col-12 mt-12 md:col-6 lg:col-3\">\r\n");
      out.write("        <a href=\"index.html\">\r\n");
      out.write("          <img src=\"images/logo.svg\" alt=\"\" />\r\n");
      out.write("        </a>\r\n");
      out.write("        <p class=\"mt-6\">\r\n");
      out.write("          Lorem ipsum dolor sit sed dmi amet, consectetur adipiscing. Cdo\r\n");
      out.write("          tellus, sed condimentum volutpat.\r\n");
      out.write("        </p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-12 mt-12 md:col-6 lg:col-3\">\r\n");
      out.write("        <h6>Socials</h6>\r\n");
      out.write("        <p>themefisher@gmail.com</p>\r\n");
      out.write("        <ul class=\"social-icons mt-4 lg:mt-6\">\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"#\">\r\n");
      out.write("              <svg\r\n");
      out.write("                width=\"19\"\r\n");
      out.write("                height=\"21\"\r\n");
      out.write("                viewBox=\"0 0 20 21\"\r\n");
      out.write("                fill=\"none\"\r\n");
      out.write("                xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("              >\r\n");
      out.write("                <path\r\n");
      out.write("                  d=\"M19.1056 10.4495C19.1056 5.09642 15 0.759277 9.9327 0.759277C4.86539 0.759277 0.759766 5.09642 0.759766 10.4495C0.759766 15.2946 4.08865 19.3191 8.49018 20.0224V13.2627H6.15996V10.4495H8.49018V8.33951C8.49018 5.91696 9.85872 4.54939 11.93 4.54939C12.9657 4.54939 14.0013 4.74476 14.0013 4.74476V7.12823H12.8547C11.7081 7.12823 11.3382 7.87063 11.3382 8.65209V10.4495H13.8904L13.4835 13.2627H11.3382V20.0224C15.7398 19.3191 19.1056 15.2946 19.1056 10.4495Z\"\r\n");
      out.write("                  fill=\"#222222\"\r\n");
      out.write("                />\r\n");
      out.write("              </svg>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"#\">\r\n");
      out.write("              <svg\r\n");
      out.write("                width=\"19\"\r\n");
      out.write("                height=\"15\"\r\n");
      out.write("                viewBox=\"0 0 19 15\"\r\n");
      out.write("                fill=\"none\"\r\n");
      out.write("                xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("              >\r\n");
      out.write("                <path\r\n");
      out.write("                  d=\"M16.3308 3.92621C17.0129 3.42889 17.6269 2.83209 18.1044 2.13583C17.4904 2.40108 16.7742 2.60001 16.0579 2.66632C16.8083 2.2353 17.354 1.5722 17.6269 0.743317C16.9447 1.14118 16.1603 1.43958 15.3758 1.60535C14.6937 0.909093 13.7728 0.51123 12.7496 0.51123C10.7714 0.51123 9.16837 2.06952 9.16837 3.99252C9.16837 4.25777 9.20248 4.52301 9.27069 4.78825C6.3034 4.62247 3.64307 3.22995 1.86952 1.14118C1.56256 1.63851 1.39202 2.2353 1.39202 2.8984C1.39202 4.09199 2.00595 5.15296 2.99504 5.7829C2.41523 5.74975 1.83541 5.61713 1.35792 5.35189V5.38504C1.35792 7.07596 2.58576 8.46847 4.22289 8.80002C3.95003 8.86633 3.60897 8.93265 3.302 8.93265C3.06326 8.93265 2.85862 8.89949 2.61987 8.86633C3.06326 10.2589 4.39342 11.2535 5.96233 11.2867C4.73449 12.215 3.19968 12.7786 1.52845 12.7786C1.22149 12.7786 0.948636 12.7455 0.675781 12.7123C2.24469 13.707 4.12057 14.2706 6.16698 14.2706C12.7496 14.2706 16.3308 8.99896 16.3308 4.39039C16.3308 4.22461 16.3308 4.09199 16.3308 3.92621Z\"\r\n");
      out.write("                  fill=\"#222222\"\r\n");
      out.write("                />\r\n");
      out.write("              </svg>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"#\">\r\n");
      out.write("              <svg\r\n");
      out.write("                width=\"19\"\r\n");
      out.write("                height=\"16\"\r\n");
      out.write("                viewBox=\"0 0 19 16\"\r\n");
      out.write("                fill=\"none\"\r\n");
      out.write("                xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("              >\r\n");
      out.write("                <path\r\n");
      out.write("                  d=\"M4.56609 15.2704V5.45315H0.948103V15.2704H4.56609ZM2.73764 4.1398C3.90474 4.1398 4.83841 3.31895 4.83841 2.33394C4.83841 1.38176 3.90474 0.59375 2.73764 0.59375C1.60945 0.59375 0.675781 1.38176 0.675781 2.33394C0.675781 3.31895 1.60945 4.1398 2.73764 4.1398ZM18.0654 15.2704H18.1044V9.8857C18.1044 7.259 17.4041 5.22331 13.7472 5.22331C11.9966 5.22331 10.8295 6.04415 10.3237 6.79933H10.2848V5.45315H6.82246V15.2704H10.4404V10.411C10.4404 9.13053 10.7128 7.91568 12.5801 7.91568C14.4475 7.91568 14.4864 9.36036 14.4864 10.5095V15.2704H18.0654Z\"\r\n");
      out.write("                  fill=\"#222222\"\r\n");
      out.write("                />\r\n");
      out.write("              </svg>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"#\">\r\n");
      out.write("              <svg\r\n");
      out.write("                width=\"19\"\r\n");
      out.write("                height=\"18\"\r\n");
      out.write("                viewBox=\"0 0 17 18\"\r\n");
      out.write("                fill=\"none\"\r\n");
      out.write("                xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("              >\r\n");
      out.write("                <path\r\n");
      out.write("                  d=\"M15.3829 10.554C15.4875 10.0381 15.5573 9.48523 15.5573 8.9324C15.5573 4.76772 12.3483 1.37701 8.40687 1.37701C7.88367 1.37701 7.36047 1.45072 6.87215 1.56129C6.20943 1.00846 5.37231 0.676758 4.50031 0.676758C2.33775 0.676758 0.59375 2.55639 0.59375 4.80458C0.59375 5.76282 0.87279 6.64735 1.39599 7.34761C1.29135 7.86359 1.22159 8.41642 1.22159 8.9324C1.22159 13.1339 4.43055 16.5246 8.37199 16.5246C8.89518 16.5246 9.41838 16.4509 9.9067 16.3404C10.5694 16.8932 11.4065 17.188 12.2785 17.188C14.4411 17.188 16.1851 15.3453 16.1851 13.0602C16.22 12.1388 15.9061 11.2543 15.3829 10.554ZM8.61615 13.9447C6.31407 13.9447 4.39567 12.8759 4.39567 11.5491C4.39567 10.9595 4.70959 10.4066 5.44207 10.4066C6.52335 10.4066 6.62799 12.0651 8.51151 12.0651C9.3835 12.0651 9.97646 11.6597 9.97646 11.1069C9.97646 10.4066 9.41838 10.2961 8.51151 10.0749C6.34895 9.48523 4.39567 9.2641 4.39567 6.86849C4.39567 4.65716 6.45359 3.84633 8.19759 3.84633C10.116 3.84633 12.0693 4.65716 12.0693 5.91024C12.0693 6.53679 11.6856 7.08962 11.0229 7.08962C10.0462 7.08962 10.0113 5.83653 8.40687 5.83653C7.49999 5.83653 6.94191 6.09452 6.94191 6.68421C6.94191 7.38446 7.67439 7.45818 9.34862 7.90044C10.7787 8.23214 12.5227 8.85869 12.5227 10.7383C12.5227 12.9128 10.5345 13.9447 8.61615 13.9447Z\"\r\n");
      out.write("                  fill=\"#222222\"\r\n");
      out.write("                />\r\n");
      out.write("              </svg>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-12 mt-12 md:col-6 lg:col-3\">\r\n");
      out.write("        <h6>Quick Links</h6>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"about.html\">About</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"#\">Category</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"#\">Testimonial</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"contact.html\">Contact</a>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-12 mt-12 md:col-6 lg:col-3\">\r\n");
      out.write("        <h6>Location & Contact</h6>\r\n");
      out.write("        <p>2118 Thornridge Cir. Syracuse, Connecticut 35624</p>\r\n");
      out.write("        <p>(704) 555-0127</p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"container max-w-[1440px]\">\r\n");
      out.write("    <div\r\n");
      out.write("      class=\"footer-copyright mx-auto border-t border-border pb-10 pt-7 text-center\"\r\n");
      out.write("    >\r\n");
      out.write("      <p>Designed And Developed by <a href=\"https://themefisher.com\" target=\"_blank\">Themefisher</a></p>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</footer>");
      out.write("	\r\n");
      out.write("	<script>\r\n");
      out.write("\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
