/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-04-23 05:22:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/inc/asset.jsp", Long.valueOf(1713849773742L));
    _jspx_dependants.put("jar:file:/C:/Users/user/Desktop/goodjob/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/GoodJob/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/inc/header.jsp", Long.valueOf(1713849313899L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1713848819034L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- favicon -->\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"/good/asset/images/favicon.png\" />\r\n");
      out.write("\r\n");
      out.write("<!-- theme meta -->\r\n");
      out.write("<meta name=\"theme-name\" content=\"Pinwheel\" />\r\n");
      out.write("<meta name=\"msapplication-TileColor\" content=\"#000000\" />\r\n");
      out.write("<meta name=\"theme-color\" media=\"(prefers-color-scheme: light)\"\r\n");
      out.write("	content=\"#fff\" />\r\n");
      out.write("<meta name=\"theme-color\" media=\"(prefers-color-scheme: dark)\"\r\n");
      out.write("	content=\"#000\" />\r\n");
      out.write("<meta name=\"generator\" content=\"gulp\" />\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("\r\n");
      out.write("<!-- responsive meta -->\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, maximum-scale=5\" />\r\n");
      out.write("\r\n");
      out.write("<!-- title -->\r\n");
      out.write("<title>Good Job</title>\r\n");
      out.write("\r\n");
      out.write("<!-- noindex robots -->\r\n");
      out.write("<meta name=\"robots\" content=\"\" />\r\n");
      out.write("\r\n");
      out.write("<!-- meta-description -->\r\n");
      out.write("<meta name=\"description\" content=\"meta description\" />\r\n");
      out.write("\r\n");
      out.write("<!-- author from config.json -->\r\n");
      out.write("<meta name=\"author\" content=\"{config.metadata.meta_author}\" />\r\n");
      out.write("\r\n");
      out.write("<!-- og-title -->\r\n");
      out.write("<meta property=\"og:title\" content=\"\" />\r\n");
      out.write("\r\n");
      out.write("<!-- og-description -->\r\n");
      out.write("<meta property=\"og:description\" content=\"\" />\r\n");
      out.write("<meta property=\"og:type\" content=\"website\" />\r\n");
      out.write("<meta property=\"og:url\" content=\"/\" />\r\n");
      out.write("\r\n");
      out.write("<!-- twitter-title -->\r\n");
      out.write("<meta name=\"twitter:title\" content=\"\" />\r\n");
      out.write("\r\n");
      out.write("<!-- twitter-description -->\r\n");
      out.write("<meta name=\"twitter:description\" content=\"\" />\r\n");
      out.write("\r\n");
      out.write("<!-- og-image -->\r\n");
      out.write("<meta property=\"og:image\" content=\"\" />\r\n");
      out.write("\r\n");
      out.write("<!-- twitter-image -->\r\n");
      out.write("<meta name=\"twitter:image\" content=\"\" />\r\n");
      out.write("<meta name=\"twitter:card\" content=\"summary_large_image\" />\r\n");
      out.write("\r\n");
      out.write("<!-- google font css -->\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\" />\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin />\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\" />\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Merriweather:wght@700;900&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("<!-- styles -->\r\n");
      out.write("\r\n");
      out.write("<!-- Swiper slider -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/good/asset/plugins/swiper/swiper-bundle.css\" />\r\n");
      out.write("\r\n");
      out.write("<!-- Fontawesome -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/good/asset/plugins/font-awesome/v6/brands.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/good/asset/plugins/font-awesome/v6/solid.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/good/asset/plugins/font-awesome/v6/fontawesome.css\" />\r\n");
      out.write("\r\n");
      out.write("<!-- Main Stylesheet -->\r\n");
      out.write("<link href=\"/good/asset/styles/main.css\" rel=\"stylesheet\" />");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<header class=\"header\">\r\n");
      out.write("  <nav class=\"navbar container\">\r\n");
      out.write("    <!-- logo -->\r\n");
      out.write("    <div class=\"order-0\">\r\n");
      out.write("      <a href=\"index.html\">\r\n");
      out.write("        <img src=\"images/logo.svg\" height=\"30\" width=\"147\" alt=\"logo\" />\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- navbar toggler -->\r\n");
      out.write("    <input id=\"nav-toggle\" type=\"checkbox\" class=\"hidden\" />\r\n");
      out.write("    <label\r\n");
      out.write("      id=\"show-button\"\r\n");
      out.write("      for=\"nav-toggle\"\r\n");
      out.write("      class=\"order-1 flex cursor-pointer items-center lg:order-1 lg:hidden\"\r\n");
      out.write("    >\r\n");
      out.write("      <svg class=\"h-6 fill-current\" viewBox=\"0 0 20 20\">\r\n");
      out.write("        <title>Menu Open</title>\r\n");
      out.write("        <path d=\"M0 3h20v2H0V3z m0 6h20v2H0V9z m0 6h20v2H0V0z\"></path>\r\n");
      out.write("      </svg>\r\n");
      out.write("    </label>\r\n");
      out.write("    <label\r\n");
      out.write("      id=\"hide-button\"\r\n");
      out.write("      for=\"nav-toggle\"\r\n");
      out.write("      class=\"order-2 hidden cursor-pointer items-center lg:order-1\"\r\n");
      out.write("    >\r\n");
      out.write("      <svg class=\"h-6 fill-current\" viewBox=\"0 0 20 20\">\r\n");
      out.write("        <title>Menu Close</title>\r\n");
      out.write("        <polygon\r\n");
      out.write("          points=\"11 9 22 9 22 11 11 11 11 22 9 22 9 11 -2 11 -2 9 9 9 9 -2 11 -2\"\r\n");
      out.write("          transform=\"rotate(45 10 10)\"\r\n");
      out.write("        ></polygon>\r\n");
      out.write("      </svg>\r\n");
      out.write("    </label>\r\n");
      out.write("    <!-- /navbar toggler -->\r\n");
      out.write("    <ul\r\n");
      out.write("      id=\"nav-menu\"\r\n");
      out.write("      class=\"navbar-nav order-2 hidden w-full flex-[0_0_100%] lg:order-1 lg:flex lg:w-auto lg:flex-auto lg:justify-center lg:space-x-5\"\r\n");
      out.write("    >\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a href=\"\" class=\"nav-link active\">Home</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a href=\"about.html\" class=\"nav-link\">About</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a href=\"blog.html\" class=\"nav-link\">Blog</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a href=\"features.html\" class=\"nav-link\">Features</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a href=\"how-it-works.html\" class=\"nav-link\">How It Works</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item nav-dropdown group relative\">\r\n");
      out.write("        <span class=\"nav-link inline-flex items-center\">\r\n");
      out.write("          Pages\r\n");
      out.write("          <svg class=\"h-4 w-4 fill-current\" viewBox=\"0 0 20 20\">\r\n");
      out.write("            <path\r\n");
      out.write("              d=\"M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z\"\r\n");
      out.write("            />\r\n");
      out.write("          </svg>\r\n");
      out.write("        </span>\r\n");
      out.write("        <ul\r\n");
      out.write("          class=\"nav-dropdown-list hidden group-hover:block lg:invisible lg:absolute lg:block lg:opacity-0 lg:group-hover:visible lg:group-hover:opacity-100\"\r\n");
      out.write("        >\r\n");
      out.write("          <li class=\"nav-dropdown-item\">\r\n");
      out.write("            <a href=\"career.html\" class=\"nav-dropdown-link\">Career</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-dropdown-item\">\r\n");
      out.write("            <a href=\"career-single.html\" class=\"nav-dropdown-link\"\r\n");
      out.write("              >Career Single</a\r\n");
      out.write("            >\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-dropdown-item\">\r\n");
      out.write("            <a href=\"integrations.html\" class=\"nav-dropdown-link\"\r\n");
      out.write("              >Integrations</a\r\n");
      out.write("            >\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-dropdown-item\">\r\n");
      out.write("            <a href=\"integration-single.html\" class=\"nav-dropdown-link\"\r\n");
      out.write("              >Integration Single</a\r\n");
      out.write("            >\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-dropdown-item\">\r\n");
      out.write("            <a href=\"pricing.html\" class=\"nav-dropdown-link\">Pricing</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-dropdown-item\">\r\n");
      out.write("            <a href=\"changelogs.html\" class=\"nav-dropdown-link\">Changelogs</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-dropdown-item\">\r\n");
      out.write("            <a href=\"terms-conditions.html\" class=\"nav-dropdown-link\"\r\n");
      out.write("              >Terms & Conditions</a\r\n");
      out.write("            >\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a href=\"contact.html\" class=\"nav-link\">Contact</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item mt-3.5 lg:hidden\">\r\n");
      out.write("        <a class=\"btn btn-white btn-sm border-border\" href=\"signin.html\"\r\n");
      out.write("          >Sing Up Now</a\r\n");
      out.write("        >\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    <div class=\"order-1 ml-auto hidden items-center md:order-2 md:ml-0 lg:flex\">\r\n");
      out.write("      <a class=\"btn btn-white btn-sm\" href=\"signin.html\">Sing Up Now</a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>\r\n");
      out.write("</header>");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.7.1.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
